import Link from "next/link";

export const metadata = {
  title: "Citadel — your sovereign inbox",
  description:
    "Private, sovereign email for everyone — built to a regulated-professional standard. The AI runs on infrastructure you control, and forgets on a schedule you can prove.",
};

export default function Landing() {
  return (
    <>
      <header className="mk-topbar">
        <div className="mk-topbar-inner">
          <Link href="/" className="brand">
            <span className="logo" aria-hidden>C</span>
            <span className="brand-text">
              <b>Citadel</b>
              <small>Your sovereign inbox</small>
            </span>
          </Link>
          <nav className="mk-nav">
            <a href="#how">How it works</a>
            <a href="#pricing">Pricing</a>
            <Link className="btn-primary btn-small" href="/inbox">Open Citadel</Link>
          </nav>
        </div>
      </header>

      <div className="mk">
      <section className="mk-hero">
        <div className="mk-eyebrow">Sovereign email · AI you host yourself</div>
        <h1 className="mk-h1">
          The inbox
          <br />
          that <em>forgets</em>.
        </h1>
        <p className="mk-lede">
          Citadel reads your mail to triage it and draft your replies, then deletes what it
          learned on a schedule you set — and proves it&rsquo;s gone. The AI runs on infrastructure
          you control. Nothing is sent to a US cloud. No copies are left behind.
        </p>
        <div className="mk-cta-row">
          <Link className="btn-primary" href="/inbox">Open Citadel</Link>
          <a className="btn-secondary" href="#how">See how it works</a>
        </div>

        <div className="mk-preview" aria-hidden>
          <div className="mk-preview-bar"><span /><span /><span /></div>
          <div className="card" style={{ margin: 0 }}>
            <div className="item-head">
              <div>
                <div className="item-from">Jordan Lee &lt;jordan@client.example&gt;</div>
                <div className="item-subject">Re: settlement timeline</div>
              </div>
              <div className="item-meta">9:24 AM</div>
            </div>
            <div className="badges">
              <span className="badge p-Urgent">Urgent</span>
              <span className="badge label">Client matter</span>
            </div>
            <div className="summary">
              Client asks to confirm the filing deadline this Thursday and whether the revised draft
              is ready to send.
            </div>
          </div>
        </div>
      </section>

      <section className="mk-section">
        <h2 className="mk-h2">
          Three <span className="mk-grad">guarantees</span>, not promises
        </h2>
        <p className="mk-sub">Each one is a property of how Citadel is built — not a policy you have to trust.</p>
        <div className="mk-grid">
          <Feature
            title="The AI runs where you do"
            body="Summaries, triage and draft replies are generated by a model running on infrastructure you control — today via a local Apertus model, next on a Canadian GPU host. No US clouds. No API keys. Your mail never leaves the box you run."
          />
          <Feature
            title="It forgets, provably"
            body="Citadel keeps only what the AI derived, and seals each item under its own encryption key. When your schedule says so, that key is destroyed. There is no master copy to fall back on, so the data is gone — permanently, not in a trash folder."
          />
          <Feature
            title="The audit log carries no secrets"
            body="Every step is recorded — that a message was processed, and when it was forgotten — but never the content, the summary, or a key. You can show a regulator exactly what happened without revealing a single word of it."
          />
        </div>
      </section>

      <section className="mk-section" id="how">
        <h2 className="mk-h2">How it works</h2>
        <ol className="mk-steps">
          <Step n="1" title="Connect" body="Read-only Gmail today (Microsoft 365 next). Raw email stays in memory only — never written to disk." />
          <Step n="2" title="Process" body="The local AI writes a one-line summary, a priority, and a suggested reply for each message." />
          <Step n="3" title="Encrypt" body="Only the derived data is stored — encrypted per-item with a unique key." />
          <Step n="4" title="Forget" body="On schedule (1h / 24h / 7d / on logout) the key is destroyed — gone for good." />
          <Step n="5" title="Prove" body="The audit log shows it happened, content-free. One click proves the data is truly unrecoverable." />
        </ol>
      </section>

      <section className="mk-section" id="pricing">
        <h2 className="mk-h2">One product. Honest price.</h2>
        <p className="mk-sub">Connect a real inbox for free. Upgrade when you outgrow the cap — same privacy either way.</p>
        <div className="mk-pricing">
          <div className="mk-price">
            <div className="mk-price-name">Free</div>
            <div className="mk-price-amt">$0</div>
            <div className="mk-price-note">Connect a real inbox</div>
            <ul className="mk-price-list">
              <li>AI on up to <strong>2 emails</strong></li>
              <li>Capped text per email</li>
              <li>The full forget &amp; prove loop</li>
            </ul>
            <Link className="btn-secondary mk-price-btn" href="/inbox">Try it free</Link>
          </div>
          <div className="mk-price mk-price-featured">
            <div className="mk-price-badge">Most popular</div>
            <div className="mk-price-name">Full</div>
            <div className="mk-price-amt">$15<span>/mo</span></div>
            <div className="mk-price-note">or $10/mo paid annually</div>
            <ul className="mk-price-list">
              <li>Your full inbox</li>
              <li>Full forget scheduler &amp; semantic search</li>
              <li>Audit export</li>
              <li>Professional / compliance add-ons</li>
            </ul>
            <Link className="btn-primary mk-price-btn" href="/inbox">Get started</Link>
          </div>
        </div>
      </section>

      <section className="mk-band">
        <h2 className="mk-band-h">Take back your inbox.</h2>
        <Link className="btn-primary mk-band-btn" href="/inbox">Get started</Link>
      </section>

      <footer className="mk-footer">
        <div className="brand">
          <span className="logo" aria-hidden>C</span>
          <span className="brand-text">
            <b>Citadel</b>
            <small>Your sovereign inbox</small>
          </span>
        </div>
        <div className="mk-foot-note">
          Concept prototype · synthetic data by default · AI runs locally. © Citadel
        </div>
        <div className="mk-foot-links">
          <Link href="/privacy">Privacy</Link>
        </div>
      </footer>
      </div>
    </>
  );
}

function Feature({ title, body }: { title: string; body: string }) {
  return (
    <div className="mk-feature">
      <h3>{title}</h3>
      <p>{body}</p>
    </div>
  );
}

function Step({ n, title, body }: { n: string; title: string; body: string }) {
  return (
    <li className="mk-step">
      <span className="mk-step-n" aria-hidden>{n}</span>
      <div>
        <h4>{title}</h4>
        <p>{body}</p>
      </div>
    </li>
  );
}
